project_id = "mojbppmrfcrhpwgybhxr"

[functions.send-team-invitation]
verify_jwt = false

[functions.send-task-assignment]
verify_jwt = false

[functions.send-comment-notification]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false
